#' Tidy the result of a time-series model into a summary tibble
#'
#'
#' @param x An object to be converted into a tibble ("tidy" data.frame)
#' @param ... extra arguments
#'
#' @details
#' `sw_tidy()` methods always returns a "tidy" tibble with model coeffc.
#' The single row includes summary statistics relevent to the model accuracy,
#' which can be used to assess model fit and quality. The benefit of `sw_glance`
#' is that it has methods for various time-series model classes such as
#' `HoltWinters`, `ets`, `Arima`, etc.
#'
#' For non-time series, `sw_glance()` defaults to `broom::glance()`.
#' The only difference is that the return is a tibble.
#' The output of `sw_tidy()` is always a tibble with disposable row names. It is
#' therefore suited for further manipulation by packages like dplyr and
#' ggplot2. The `sw_tidy()` function is designed to work well with time-series
#' models (supplied via `x`). The function provides additional "tidy" functionality
#' to the `broom::tidy()` function as follows:
#'
#' 1. Model object classes such as `ets`, `Arima`, `bats`, `stl`,
#' and others from Rob Hyndman's excellent `forecast` package.
#' 2. Model object classes such as `HoltWinters` and `Arima` from the `stats`
#' package.
#'
#' @seealso [tidy()]
#'
#' @return a tibble
#'
#' @examples
#' library(forecast)
#' WWWusage %>%
#'     auto.arima() %>%
#'     sw_tidy(conf.int = TRUE)
#'
#' @export
sw_tidy <- function(x, ...) UseMethod("sw_tidy")


#' Default tidying method
#'
#' By default, `sw_tidy()` uses [broom::tidy()] to convert its output.
#'
#'
#' @param x an object to be tidied
#' @param ... extra arguments passed to `broom::tidy()`
#'
#' @return A tibble generated by [broom::tidy()]
#'
#' @export
sw_tidy.default <- function(x, ...) {
    broom::tidy(x, ...) %>%
        tibble::as_tibble()
}
