#' Extract an index of date or datetime from time series
#'
#' @name sw_unroll_index
#'
#' @param data A time-based tibble, time-series object, time-series model,
#' or `forecast` object.
#'
#' @return Returns a vector of date or date times
#'
#' @details
#' `sw_unroll_index` is used to extract the date or datetime index from various
#' time series data types.
#' The method is particularly useful for retrieving date or datetime index information
#' from `ts` objects which traditionally lose this information during coercion
#' from time-based tibble (`tbl`), `xts`, and `zoo` data types that contain
#' and index.
#' The method can additionally be used on `forecast` objects and a number of
#' objects generated by modeling functions such as `Arima`, `ets`, and `HoltWinters`
#' classes.
#'
#' __Important Note__: To gain the benefit of `sw_unroll_index()` the time series
#' must have an index. This is particularly important for `ts` objects, which
#' by default do not contain an index and therefore must be coerced from time-based
#' objects such as `tbl`, `xts`, or `zoo` using the `sw_ts()` function.
#' Refer to [sw_ts()] for creating persistent date / datetime index
#' during coercion to `ts`.
#'
#'
#'
#' @seealso [sw_ts()], [sw_tbl()], [sw_xts()], [sw_zoo()], [sw_zooreg()]
#'
#' @examples
#' library(tidyverse)
#' library(sweep)
#'
#' # Create time-based tibble
#' data_tbl <- tibble::tibble(
#'     date = seq.Date(from = as.Date("2000-01-01"), by = 1, length.out = 5),
#'     x    = rnorm(5) * 10,
#'     y    = 5:1
#' )
#' sw_unroll_index(data_tbl) # Returns time-based index vector
#'
#' # Coerce to ts using sw_ts()
#' data_ts <- sw_ts(data_tbl)
#' sw_unroll_index(data_ts)  # Returns original time-based index vector
#'
#' # Coerce to tbl with original, non-regularized time index
#' sw_tbl(data_ts, .unroll = TRUE)
#'
#' # Coerce to xts
#' data_ts %>%
#'     sw_xts(order.by = sw_unroll_index(.))
#'
#' # Coerce to xts
#' data_ts %>%
#'     sw_zoo(order.by = sw_unroll_index(.))
#'
#'
#' @export
sw_unroll_index <- function(data) {
    UseMethod("sw_unroll_index", data)
}


#' @export
sw_unroll_index.data.frame <- function(data) {

    date_var <- get_date_variables(data)

    if (length(date_var) == 0) stop("No date or date-time identified.")

    date_var <- date_var[[1]]

    # Get contents of date_var column
    ret <- data[[date_var]]

    return(ret)

}

#' @export
sw_unroll_index.ts <- function(data) {

    if (is.null(attr(data, "index"))) {
        stop("Attribute `index` not found.")
    }

    # Coerce numeric date to date-time
    ret <- attr(data, "index") %>%
        lubridate::as_datetime()

    # Set time class to date if Date class
    tclass <- attr(attr(data, "index"), "tclass")
    if (tclass == "Date") ret <- lubridate::as_date(ret)

    # Set the timezone
    tzone <- attr(attr(data, "index"), "tzone")
    lubridate::tz(ret) <- tzone

    return(ret)

}

#' @export
sw_unroll_index.zoo <- function(data) {

    ret <- sw_xts(data) %>%
        sw_unroll_index()

    return(ret)

}

#' @export
sw_unroll_index.zooreg <- function(data) {

    first_val <- rownames(data)[[1]]

    if (is.null(first_val)) {
        # bare row names
        stop("Attribute `index` not found.")
    }

    # Coerce character date to date-time
    len <- stringr::str_length(first_val)
    if (len > 10) {
        # date-time
        ret <- rownames(data) %>%
            lubridate::as_datetime()
    } else {
        # date
        ret <- rownames(data) %>%
            lubridate::as_date()
    }

    return(ret)

}

#' @export
sw_unroll_index.xts <- function(data) {

    if (is.null(attr(data, "index"))) {
        stop("Attribute `index` not found.")
    }

    # Coerce numeric class to date-time
    ret <- attr(data, "index") %>%
        lubridate::as_datetime()

    # Set time class to date if Date class
    tclass <- xts::tclass(data)
    if (tclass == "Date") ret <- lubridate::as_date(ret)

    # Set the timezone
    tzone <- xts::tzone(data)
    lubridate::tz(ret) <- tzone

    return(ret)

}

#' @export
sw_unroll_index.forecast <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.Arima <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.ets <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.stl <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.stlm <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.stlf <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.baggedETS <- function(data) {
    sw_unroll_index(data$y)
}

#' @export
sw_unroll_index.fracdiff <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.bats <- function(data) {
    sw_unroll_index(data$y)
}

#' @export
sw_unroll_index.HoltWinters <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.nnetar <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.StructTS <- function(data) {
    sw_unroll_index(data$x)
}

#' @export
sw_unroll_index.default <- function(data) {
    warning(paste0("`sw_unroll_index` is not designed to work with objects of class ", class(data), "."))
    invisible(data)
}


